update dependencies
bitshares/bitshares-ui-style-guide pull request #35
Opened 2021-12-05 11:17 UTC by xiangxn

update dependencies

2021-12-05 14:38 UTC, abitmore requested changes
Thanks.

2021-12-05 14:38 UTC, abitmore commented on package-lock.json
> +      "resolved": "https://registry.npm.taobao.org/amdefine/download/amdefine-1.0.1.tgz",
Can we stick with registry.npmjs.org?

2021-12-05 14:38 UTC, abitmore commented on package-lock.json
> +      "resolved": "https://registry.npmmirror.com/@types/normalize-package-data/download/@types/normalize-package-data-2.4.1.tgz?cache=0&sync_timestamp=1637269900376&other_urls=https%3A%2F%2Fregistry
Can we stick with registry.npmjs.org?

2022-01-05 13:50 UTC, xiangxn commented
Replaced `npm` with `yarn`, and used the source of yarn

2022-01-14 11:33 UTC, xiangxn commented
Can this `PR` be merged?

2022-01-14 11:33 UTC, sschiessl-bcp commented
Sorry, overlooked this one.

2022-01-14 11:34 UTC, merged